PREFIX xsd:    <http://www.w3.org/2001/XMLSchema#>
PREFIX :       <http://example/>
PREFIX sarq:     <http://openjena.org/SARQ/property#>
PREFIX dc:    <http://purl.org/dc/elements/1.1/>

SELECT *
{
    ?lit sarq:search ('+document' 0.7 1)
}
